# User domain    
user:
  domain: hida
  
# Spring and Spring Web MVC specific settings  
spring:
  application:
    name: homecheck
  mvc:
    throw-exception-if-no-handler-found: true
    hiddenmethod:
     filter:
      enabled: true
  resources:
    add-mappings: false
  # Spring Security settings
  security:
    user:
      name: admin
      password: pse2020
  # Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      # Max file size
      max-file-size: 200MB
      # Max request size
      max-request-size: 210MB
      # Threshold after which files are written to disk
      file-size-threshold: 10MB

# Tomcat server settings
server:
  port: 9999
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  servlet:
    context-path: /api
  # Handle HTTPS forward headers from an Apache reverse proxy
  forward-headers-strategy: NATIVE
  tomcat:
    redirect-context-root: false

# Springdoc OpenAPI settings
springdoc:
    api-docs:
        path: /api-docs
    packages-to-scan: it.ecubit.homecheck.web
    paths-to-match: /login, /refresh, /diasu/pazienti/**, /aslvt/pazienti/**, /aslvt/dispositivi/**, /utenti/**, /nazioni/**
    swagger-ui:
        path: /swagger-ui.html

# JWT settings
jwt:
    default-access-token-expiration-seconds: 3600
    default-refresh-token-expiration-seconds: 2592000
    secret: abcdefghijklmnopqrstuvwxyz123
   
DEFAULT_FRONTEND_LOCALE_LANGUAGE: ITALIAN
DEFAULT_PAGE_SIZE: 20

# LOCAL ENVIRONMENT CONFIG
---
spring:
  profiles: local
  # Mongo settings
  data:
    mongodb:
      database: pse
      host: localhost
      port: 27017

pse:
  storageBaseUrl: http://localhost:8989/api/archivio

# DEV ENVIRONMENT CONFIG
---
spring:
  profiles: dev
  config:
    import: configserver:http://localhost:8888
    retry:
      max-attempts: 10
      initial-interval: 6000
      max-interval: 6000
      # fail if didnt find configserver
    fail-fast: true
  data:
    mongodb:
      database: pse
      host: localhost
      port: 27017

# Eureka Server settings
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
            
pse:
  storageBaseUrl: http://ec200601.seewebcloud.it:8989/api/archivio

# TEST ENVIRONMENT CONFIG
---
spring:
  profiles: test
  config:
    import: configserver:http://mystic-config-server:8888
    discovery:
      enabled: true
      serviceId: mystic-config-server
    retry:
      max-attempts: 10
      initial-interval: 6000
      max-interval: 6000
      # fail if didnt find configserver
    fail-fast: true
  data:
    mongodb:
      uri: mongodb://pse-mongo-1-test:27017,pse-mongo-2-test:27017,pse-mongo-3-test:27017/?replicaSet=pse-mongo-set&retryWrites=true
      database: pse
  sleuth:
    sampler:
      probability: 1.0
            
pse:
  storageBaseUrl: http://ec200601.seewebcloud.it:8989/api/archivio
  
# Eureka Server settings
eureka:
  client:
    serviceUrl:
      defaultZone: http://mystic-eureka:8761/eureka

# PROD ENVIRONMENT CONFIG
---
spring:
  profiles: prod
  config:
    import: configserver:http://mystic-config-server:8888
    discovery:
      enabled: true
      serviceId: mystic-config-server
    retry:
      max-attempts: 10
      initial-interval: 6000
      max-interval: 6000
      # fail if didnt find configserver
    fail-fast: true
  data:
    mongodb:
      uri: mongodb://pse-mongo-1-prod:27017,pse-mongo-2-prod:27017,pse-mongo-3-prod:27017/?replicaSet=pse-mongo-set&retryWrites=true
      database: pse
  sleuth:
    sampler:
      probability: 1.0
  inetutils:
      preferred-networks: pse-cloud-net
            
pse:
  storageBaseUrl: http://ec200601.seewebcloud.it:8989/api/archivio
  
# Eureka Server settings
eureka:
  client:
    serviceUrl:
      defaultZone: http://mystic-eureka:8761/eureka
  instance:
    secure-port-enabled: false
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    #health-check-url: http://${config.eureka.instance.hostname:localhost}:${eureka.instance.non-secure-port}/actuator/health
    status-page-url: http://localhost:${eureka.instance.non-secure-port}/actuator/info

